@RESTAPI_HostAddress = http://localhost:5088

GET {{RESTAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{RESTAPI_HostAddress}}/book
Accept: application/json

###
GET {{RESTAPI_HostAddress}}/book/4
Accept: application/json

###
POST {{RESTAPI_HostAddress}}/book
Content-Type: application/json
{
  "id": 4,
  "title": "New Book Title",
  "author": "Author Name",
  "yearPublished": 2026
}

###
PUT {{RESTAPI_HostAddress}}/book/4
Content-Type: application/json
{
  "id": 4,
  "title": "Updated Book Title",
  "author": "Updated Author Name",
  "yearPublished": 2027
}